# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Greg Wiedeman
author: Gregory Wiedeman
email: gwiedeman@albany.edu
description: >- # this means to ignore newlines until "baseurl:"
  I'm an archivist who works to make information more accessible.
#baseurl: "gwiedeman.github.io" # the subpath of your site, e.g. /blog
url: "http://gregwiedeman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gregwiedeman
github_username:  gwiedeman

# Build settings
#theme: minima
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/writing/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  presentations:
    output: true
  code:
    output: true

header_pages:
  - about.md
  - writing.md
  - presentations.md
  - code.md
  - cv.md

defaults:
  - scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentations"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      background: '/assets/images/2019-04-25_13-04-26-0.JPG'
  - scope:
      path: "presentations"
    values:
      background: '/assets/images/2019-04-26 09-42-43-0.JPG'
  - scope:
      path: "/code"
    values:
      background: '/assets/images/2019-04-25 12-50-04-0.JPG'
      #background: '/assets/images/2019-04-23 15-26-16-0.JPG'